[package]
name = "qutex"
version = "0.0.1"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
license = "MIT"
description = """\
	Synchronization mechanisms that rely on lock-free queues to guarantee \
	mutually exclusive or shared exclusive access to data."""


[dependencies]
crossbeam = "0.2"
futures = "0.1"