[package]
name = "qutex"
version = "0.0.2"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
license = "MIT"
description = """\
	Synchronization mechanisms that rely on lock-free queues to guarantee \
	mutually exclusive or shared exclusive access to data."""
documentation = "https://docs.rs/qutex"
homepage = "https://github.com/cogciprocate/qutex"
repository = "https://github.com/cogciprocate/qutex"
readme = "README.md"
keywords = ["futures", "mutex", "lock"]

[dependencies]
crossbeam = "0.2"
futures = "0.1"